### ISSUE TITLE
brog45

### ISSUE THREAD

**Issue by aindilis** [brog45/homelessExpertSystem#1]
Hi brog45,

This project looks wonderful!  I'd just like to check in and ask whether you have finished development of it or plan to continue working on it?  If you are done, I'd like to fork and begin working on trying to extend it for use within a project I'm working on called "The Free Life Planner" which caters in part to the homeless.  Thanks again, this is truly wonderful!

Regards,
aindilis

**Comment by brog45** [comment]
Thanks! I am not done; my efforts have temporarily paused while I deal with other things. You're welcome to freely fork this repo, use copies of the code, and modify it however you like. I'm glad if it helps you.

**Comment by brog45** [comment]
Also, this is a learning side-project for me, so I would recommend you not wait until I'm "done." Help yourself to whatever is useful.
