### ISSUE TITLE
enabling goal to return to initial position causes planner to run for 15 minutes without completing

### ISSUE THREAD

**Issue by brog45** [brog45/homelessExpertSystem#2]
I'm working in `run_text.pl`. It runs in less than 3 seconds, until I try adding a goal to return to the initial position. This goal is currently commented out. I tried profiling `go` and I think it said (if I'm reading it correctly) it was spending over 40% on garbage collection. When I try `gdebug, go.`, it raises an exception when the stack hits 1GB. It crashes on `append/3` in `process_queue/4`. Maybe memory efficiency could be improved by rewriting `process_queue` to use a difference list with a tail call. Still, I don't think the memory is the cause of the problem. I think it should be able to find its way back in double time or less. 
@Anniepoo, do you have any suggestions?

**Comment by Anniepoo** [comment]
some undefines, something not checked in?

Warning: [Thread pce] The predicates below are not defined. If these are defined
Warning: [Thread pce] at runtime using assert/1, use :- dynamic Name/Arity.
Warning: [Thread pce] 
Warning: [Thread pce] generate_story/2, which is referenced by
Warning: [Thread pce] 	/home/anniepoo/homelessExpertSystem/run.pl:60:4: 1-st clause of reply_story/2
Warning: [Thread pce] init/4, which is referenced by
Warning: [Thread pce] 	/home/anniepoo/homelessExpertSystem/run.pl:59:4: 1-st clause of reply_story/2

**Comment by brog45** [comment]
The code in `run.pl` has not yet been updated. I should have just deleted it. Please use `run_text.pl` instead. Sorry for that.

**Comment by brog45** [comment]
I have deleted that and the old story data, to avoid confusion.

**Comment by brog45** [comment]
I had added a "wait" action that had no prerequisites and no negative prerequisites. It was generating too many possible plans. I removed it and what had taken 2.784 seconds suddenly took 0.076 seconds. Then I re-enabled the `goal(visited(mens_shelter))` and it ran to completion in 40.538 seconds. This is not what I had hoped, but is good enough to call this specific issue fixed, I think.

**Comment by brog45** [comment]
Now I just need to figure out how to code for a more flexible idea of time.

**Comment by Anniepoo** [comment]
yeah, 40 sec is something REALLY inefficient.
Try running in the debugger, hold down the space key and watch it for a while, maybe you'll see the inefficiency
